openapi: 3.0.0
info:
  title: Test API
  version: 1.0.0
servers:
- description: Optional server description
  url: http://api.test.com/v1
paths:
  /users:
    get:
      description: Optional longer description in CommonMark or HTML
      operationId: getUserList
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
          description: a JSON array of user names
      summary: Returns a list of users.
    post:
      operationId: createUser
      requestBody:
        $ref: '#/components/requestBodies/inline_object'
        content:
          application/json:
            schema:
              properties:
                username:
                  type: string
              type: object
        required: true
      responses:
        "201":
          description: Created
      summary: Creates a user.
  /users/{userId}:
    get:
      operationId: getUserByID
      parameters:
      - description: Parameter description CommonMark or HTML.
        explode: false
        in: path
        name: userId
        required: true
        schema:
          format: int64
          minimum: 1
          type: integer
        style: simple
      responses:
        "200":
          description: OK
      summary: Return a user by ID.
components:
  requestBodies:
    inline_object:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_object'
      required: true
  schemas:
    inline_object:
      properties:
        username:
          type: string
      type: object
